version: "3"
services:
  pg:
    image: "postgres:12.1-alpine"
    environment:
      POSTGRES_DB: pento
    ports:
      - "5432:5432"
    networks:
      - "pento"
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "dba@pento.com"
      PGADMIN_DEFAULT_PASSWORD: "dba"
    ports:
      - "33333:80"
    networks:
      - "pento"
  backend:
    build:
      context: "."
      dockerfile: "backend/Dockerfile"
    environment:
      DATABASE_ADDR: "postgres://postgres@pg:5432/pento?sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - "pento"
    depends_on:
      - "pg"

networks:
  pento:
